### ISSUE TITLE
Redirect from Azure Container Registry causes JSON parser fail

### ISSUE THREAD

**Issue by craigminihan** [klausmeyer/docker-registry-browser#245]
I've pointed a docker-registry-browser 1.3.0 instance at Azure Container Registry (ACR) and get a `We're sorry, but something went wrong.` in the UI when clicking on an image tag.

The log shows:
```
access-control-expose-headers: "Docker-Content-Digest, WWW-Authenticate, Link, X-Ms-Correlation-Request-Id"
docker-distribution-api-version: "registry/2.0"
location: "https://eusmanaged50.blob.core.windows.net/..."
strict-transport-security: "max-age=31536000; includeSubDomains, max-age=31536000; includeSubDomains"
x-content-type-options: "nosniff"
x-ms-correlation-request-id: "..."
I, [2019-11-28T21:51:14.138592 #1]  INFO -- : [efa4f1cd-14a4-49b3-8093-19846ef7f4e6] Completed 500 Internal Server Error in 1562ms (Allocations: 3814)
F, [2019-11-28T21:51:14.140040 #1] FATAL -- : [efa4f1cd-14a4-49b3-8093-19846ef7f4e6]   
[efa4f1cd-14a4-49b3-8093-19846ef7f4e6] JSON::ParserError (767: unexpected token at '<a href="https://eusmanaged50.blob.core.windows.net/...">Temporary Redirect</a>.
'):
[efa4f1cd-14a4-49b3-8093-19846ef7f4e6]   
[efa4f1cd-14a4-49b3-8093-19846ef7f4e6] app/models/tag.rb:22:in `find'
[efa4f1cd-14a4-49b3-8093-19846ef7f4e6] app/controllers/tags_controller.rb:21:in `find_tag'
```
It appears the redirect isn't followed and the response is instead parsed as JSON which fails.

**Comment by klausmeyer** [comment]
Thank you for reporting and even providing a fix 😁 

I've merged your PR and it will be available as `latest` docker image soon.
