### ISSUE TITLE
config/puma.rb:44:in `_load_from': uninitialized constant #<Class:#<Puma::DSL:0x0...>>::Rails (NameError)

### ISSUE THREAD

**Issue by JoachimVeulemans** [klausmeyer/docker-registry-browser#284]
```
JoachimVeulemans@SYNO1:~$ sudo docker run klausmeyer/docker-registry-browser
config/puma.rb:44:in `_load_from': uninitialized constant #<Class:#<Puma::DSL:0x0000562222a3a058>>::Rails (NameError)
        from /usr/local/bundle/gems/puma-4.3.3/lib/puma/dsl.rb:46:in `instance_eval'
        from /usr/local/bundle/gems/puma-4.3.3/lib/puma/dsl.rb:46:in `_load_from'
        from /usr/local/bundle/gems/puma-4.3.3/lib/puma/configuration.rb:195:in `block in load'
        from /usr/local/bundle/gems/puma-4.3.3/lib/puma/configuration.rb:195:in `each'
        from /usr/local/bundle/gems/puma-4.3.3/lib/puma/configuration.rb:195:in `load'
        from /usr/local/bundle/gems/puma-4.3.3/lib/puma/launcher.rb:58:in `initialize'
        from /usr/local/bundle/gems/puma-4.3.3/lib/puma/cli.rb:71:in `new'
        from /usr/local/bundle/gems/puma-4.3.3/lib/puma/cli.rb:71:in `initialize'
        from /usr/local/bundle/gems/puma-4.3.3/bin/puma:8:in `new'
        from /usr/local/bundle/gems/puma-4.3.3/bin/puma:8:in `<top (required)>'
        from /usr/local/bundle/bin/puma:23:in `load'
        from /usr/local/bundle/bin/puma:23:in `<main>'
```

Did a pull before so image is up to date. Worked before last update of tag 'latest'.

Thanks in advance

**Comment by klausmeyer** [comment]
Hi Joachim,

thanks for reporting that issue. I must have caused this issue with a recent change.
Will have a look ASAP.

Best, Klaus

**Comment by klausmeyer** [comment]
@JoachimVeulemans should be fixed now in `latest` tag.

Could you please pull and verify?

**Comment by JoachimVeulemans** [comment]
@klausmeyer issue is fixed! Many thanks!
