### ISSUE TITLE
Can't See Delete Button

### ISSUE THREAD

**Issue by netlander** [klausmeyer/docker-registry-browser#328]
After setting up this Registry UI as described in the readme I am not able to see all the options as can be seen in the screenshots. Namely the delete image button (if I'm not mistaken in kinda comes into view of a split second then disappears).

Here's the Docker command used for running the image:
```
docker run \
  -d \
  -e ENV_DOCKER_REGISTRY_HOST=192.168.1.14 \
  -e ENV_DOCKER_REGISTRY_PORT=5000 \
  -p 8080:80 \
  konradkleine/docker-registry-frontend:v2
```

Looks like might be missing an option but can't find it anywhere in the docs.

**Comment by klausmeyer** [comment]
Hey @netlander,

as per your provided docker run command it looks like as if you're actually using another project providing a docker frontend and not my application ;) (`konradkleine/docker-registry-frontend:v2` instead of `klausmeyer/docker-registry-browser:latest`).

Guess you should report the issue here instead:
https://github.com/kwk/docker-registry-frontend/issues

Cheers, Klaus

**Comment by netlander** [comment]
Hey @klausmeyer,
Yes I was, sorry about the confusion.
However I have switched to your repo a while ago and although I can see the delete button, I'm still not able to delete any tags.
The registry is running in 'unsecure' mode by adding the following to `/etc/docker/daemon.json`:
```
{
  "insecure-registries" : ["myregistrydomain.com:5000"]
}
```
Here is the relevant error and stack trace:

![image](https://user-images.githubusercontent.com/4721044/97150140-9f7f7c00-1765-11eb-8447-45d41a36ff08.png)
```
I, [2020-10-26T08:30:50.918178 #1]  INFO -- : [823841ca-7ab2-4d76-aec2-8d9339d9089e] Started DELETE "/repo/custom-nginx-proxy/tag/0.0.2" for 192.168.1.5 at 2020-10-26 08:30:50 +0000
I, [2020-10-26T08:30:50.920178 #1]  INFO -- : [823841ca-7ab2-4d76-aec2-8d9339d9089e] Processing by TagsController#destroy as HTML
I, [2020-10-26T08:30:50.920464 #1]  INFO -- : [823841ca-7ab2-4d76-aec2-8d9339d9089e]   Parameters: {"authenticity_token"=>"H8tJ7sh4nKJu0k+zltMISqdailez5rwaiIY+lXhDvrz9PPc+GP+ZSKiRo+cc6oYB2Hx7jEfuwf1p0Oxndi9L7A==", "repo"=>"custom-nginx-proxy", "tag"=>"0.0.2"}
I, [2020-10-26T08:30:50.927955 #1]  INFO -- request: GET http://192.168.1.9:5000/v2/custom-nginx-proxy/tags/list
I, [2020-10-26T08:30:50.928090 #1]  INFO -- request: User-Agent: "Faraday v1.0.1"
I, [2020-10-26T08:30:50.973260 #1]  INFO -- response: Status 200
I, [2020-10-26T08:30:50.973413 #1]  INFO -- response: content-type: "application/json; charset=utf-8"
docker-distribution-api-version: "registry/2.0"
x-content-type-options: "nosniff"
date: "Mon, 26 Oct 2020 08:30:50 GMT"
content-length: "47"
I, [2020-10-26T08:30:50.975160 #1]  INFO -- request: GET http://192.168.1.9:5000/v2/custom-nginx-proxy/manifests/0.0.2
I, [2020-10-26T08:30:50.975294 #1]  INFO -- request: User-Agent: "Faraday v1.0.1"
Accept: "application/vnd.docker.distribution.manifest.v2+json"
I, [2020-10-26T08:30:51.021235 #1]  INFO -- response: Status 200
I, [2020-10-26T08:30:51.021407 #1]  INFO -- response: content-length: "2621"
content-type: "application/vnd.docker.distribution.manifest.v2+json"
docker-content-digest: "sha256:e05a10e8efc5e4607e0af74edf5a0f0d6eb7536fdefcf7ab1edfc90037782e72"
docker-distribution-api-version: "registry/2.0"
etag: "\"sha256:e05a10e8efc5e4607e0af74edf5a0f0d6eb7536fdefcf7ab1edfc90037782e72\""
x-content-type-options: "nosniff"
date: "Mon, 26 Oct 2020 08:30:51 GMT"
I, [2020-10-26T08:30:51.023041 #1]  INFO -- request: GET http://192.168.1.9:5000/v2/custom-nginx-proxy/blobs/sha256:51535d2074b8e7e5ea79935f77c0a1c364e9d112987747ff0b683c364f278094
I, [2020-10-26T08:30:51.023175 #1]  INFO -- request: User-Agent: "Faraday v1.0.1"
I, [2020-10-26T08:30:51.072807 #1]  INFO -- response: Status 200
I, [2020-10-26T08:30:51.072985 #1]  INFO -- response: accept-ranges: "bytes"
cache-control: "max-age=31536000"
content-length: "9977"
content-type: "application/octet-stream"
docker-content-digest: "sha256:51535d2074b8e7e5ea79935f77c0a1c364e9d112987747ff0b683c364f278094"
docker-distribution-api-version: "registry/2.0"
etag: "\"sha256:51535d2074b8e7e5ea79935f77c0a1c364e9d112987747ff0b683c364f278094\""
x-content-type-options: "nosniff"
date: "Mon, 26 Oct 2020 08:30:51 GMT"
I, [2020-10-26T08:30:51.088264 #1]  INFO -- request: DELETE http://192.168.1.9:5000/v2/custom-nginx-proxy/manifests/sha256:e05a10e8efc5e4607e0af74edf5a0f0d6eb7536fdefcf7ab1edfc90037782e72
I, [2020-10-26T08:30:51.088410 #1]  INFO -- request: User-Agent: "Faraday v1.0.1"
I, [2020-10-26T08:30:51.134198 #1]  INFO -- : [823841ca-7ab2-4d76-aec2-8d9339d9089e] Completed 500 Internal Server Error in 213ms (Allocations: 4714)
F, [2020-10-26T08:30:51.140734 #1] FATAL -- : [823841ca-7ab2-4d76-aec2-8d9339d9089e]
[823841ca-7ab2-4d76-aec2-8d9339d9089e] Faraday::ClientError (the server responded with status 405):
[823841ca-7ab2-4d76-aec2-8d9339d9089e]
[823841ca-7ab2-4d76-aec2-8d9339d9089e] app/models/tag.rb:59:in `delete'
[823841ca-7ab2-4d76-aec2-8d9339d9089e] app/controllers/tags_controller.rb:10:in `destroy'
```

**Comment by klausmeyer** [comment]
Ah ok :)

To have the deletion working you'll also need to enable that feature in the registry itself (it's disabled by default):
https://docs.docker.com/registry/configuration/#delete

**Comment by netlander** [comment]
Worked like a charm - thanks 🥇

**Comment by klausmeyer** [comment]
You're welcome :)
