### ISSUE TITLE
This crashes on my server

### ISSUE THREAD

**Issue by dzek69** [klausmeyer/docker-registry-browser#478]
On my server (which is really a laptop) this image crashes, which is super surprising, because on my main laptop it does not.

```
dzek@srv:~$ docker run klausmeyer/docker-registry-browser
Puma starting in single mode...
* Puma version: 5.6.2 (ruby 3.1.1-p18) ("Birdie's Version")
*  Min threads: 5
*  Max threads: 5
*  Environment: production
*          PID: 1
! Unable to load application: ExecJS::RuntimeUnavailable: Could not find a JavaScript runtime. See https://github.com/rails/execjs for a list of available runtimes.
/usr/local/bundle/gems/execjs-2.8.1/lib/execjs/runtimes.rb:58:in `autodetect': Could not find a JavaScript runtime. See https://github.com/rails/execjs for a list of available runtimes. (ExecJS::RuntimeUnavailable)
        from /usr/local/bundle/gems/execjs-2.8.1/lib/execjs.rb:5:in `<module:ExecJS>'
        from /usr/local/bundle/gems/execjs-2.8.1/lib/execjs.rb:4:in `<main>'
        from /usr/local/bundle/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
        from /usr/local/bundle/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
        from /usr/local/bundle/gems/autoprefixer-rails-10.3.3.0/lib/autoprefixer-rails/processor.rb:4:in `<main>'
        from /usr/local/bundle/gems/autoprefixer-rails-10.3.3.0/lib/autoprefixer-rails.rb:39:in `require_relative'
        from /usr/local/bundle/gems/autoprefixer-rails-10.3.3.0/lib/autoprefixer-rails.rb:39:in `<main>'
        from /usr/local/bundle/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
        from /usr/local/bundle/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
        from /usr/local/bundle/gems/bootstrap-4.6.1/lib/bootstrap/engine.rb:3:in `<main>'
        from /usr/local/bundle/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
        from /usr/local/bundle/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
        from /usr/local/bundle/gems/bootstrap-4.6.1/lib/bootstrap.rb:61:in `register_rails_engine'
        from /usr/local/bundle/gems/bootstrap-4.6.1/lib/bootstrap.rb:11:in `load!'
        from /usr/local/bundle/gems/bootstrap-4.6.1/lib/bootstrap.rb:75:in `<main>'
        from /usr/local/bundle/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
        from /usr/local/bundle/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
        from /usr/local/bundle/gems/bundler-2.3.5/lib/bundler/runtime.rb:60:in `block (2 levels) in require'
        from /usr/local/bundle/gems/bundler-2.3.5/lib/bundler/runtime.rb:55:in `each'
        from /usr/local/bundle/gems/bundler-2.3.5/lib/bundler/runtime.rb:55:in `block in require'
        from /usr/local/bundle/gems/bundler-2.3.5/lib/bundler/runtime.rb:44:in `each'
        from /usr/local/bundle/gems/bundler-2.3.5/lib/bundler/runtime.rb:44:in `require'
        from /usr/local/bundle/gems/bundler-2.3.5/lib/bundler.rb:176:in `require'
        from /app/config/application.rb:16:in `<top (required)>'
        from /app/config/environment.rb:2:in `require_relative'
        from /app/config/environment.rb:2:in `<top (required)>'
        from config.ru:3:in `require_relative'
        from config.ru:3:in `block in <main>'
        from /usr/local/bundle/gems/rack-2.2.3/lib/rack/builder.rb:116:in `eval'
        from /usr/local/bundle/gems/rack-2.2.3/lib/rack/builder.rb:116:in `new_from_string'
        from /usr/local/bundle/gems/rack-2.2.3/lib/rack/builder.rb:105:in `load_file'
        from /usr/local/bundle/gems/rack-2.2.3/lib/rack/builder.rb:66:in `parse_file'
        from /usr/local/bundle/gems/puma-5.6.2/lib/puma/configuration.rb:348:in `load_rackup'
        from /usr/local/bundle/gems/puma-5.6.2/lib/puma/configuration.rb:270:in `app'
        from /usr/local/bundle/gems/puma-5.6.2/lib/puma/runner.rb:150:in `load_and_bind'
        from /usr/local/bundle/gems/puma-5.6.2/lib/puma/single.rb:44:in `run'
        from /usr/local/bundle/gems/puma-5.6.2/lib/puma/launcher.rb:182:in `run'
        from /usr/local/bundle/gems/puma-5.6.2/lib/puma/cli.rb:81:in `run'
        from /usr/local/bundle/gems/puma-5.6.2/bin/puma:10:in `<top (required)>'
        from /usr/local/bundle/bin/puma:25:in `load'
        from /usr/local/bundle/bin/puma:25:in `<main>'
```

Some version info:

```
dzek@srv:~$ uname -a
Linux srv 4.9.0-8-amd64 #1 SMP Debian 4.9.144-3.1 (2019-02-19) x86_64 GNU/Linux
dzek@srv:~$ docker --version
Docker version 18.09.4, build d14af54
```

Please tell me what else I can provide you to help fight this problem.

**Comment by klausmeyer** [comment]
Hi @dzek69,

this error was reported by others in the past: #434 and #447

It seems to be related to an incompatibility of the used docker base image with some older versions on the docker host.

Can you please try what was suggested in [this comment](https://github.com/klausmeyer/docker-registry-browser/issues/447#issuecomment-956207446) and update the containerd on your machine?

**Comment by dzek69** [comment]
Oh, I shouldn't test new things when sleepy - I totally forgot to search issues before asking 🤦🏻‍♂️ 

Thanks for the links, I updated containerd to newest thing found by my package manager (yestarday I updated docker and docker-compose) but still no luck. I'm on Debian Stretch so newest available containerd package for me is 1.4.3: https://download.docker.com/linux/debian/dists/stretch/pool/stable/amd64/

I don't know how safe (or unsafe) would be to just replace the binary from: https://github.com/containerd/containerd/releases to use new version.

So I guess I will try that patch solution.

**Comment by klausmeyer** [comment]
> Oh, I shouldn't test new things when sleepy - I totally forgot to search issues before asking 🤦🏻‍♂️

Not a problem ;)

> Thanks for the links, I updated containerd to newest thing found by my package manager (yestarday I updated docker and docker-compose) but still no luck. I'm on Debian Stretch so newest available containerd package for me is 1.4.3: https://download.docker.com/linux/debian/dists/stretch/pool/stable/amd64/

Debian Stretch is two versions behind the latest stable. Guess it won't be easy to get latest docker & containerd to work there. Maybe worth thinking about an upgrade.

> I don't know how safe (or unsafe) would be to just replace the binary from: https://github.com/containerd/containerd/releases to use new version.

I wouldn't try patching binaries. Only thing I might consider is using packages from newer versions of the OS - but that could also end in conflicts and more issues.

> So I guess I will try that patch solution.

That could be an easy workaround for now yes. Good luck with that :+1:

--

I'm going to close this issue now as it is not something I could solve.
