### ISSUE TITLE
Tag list cannot be configured to sort by `version`

### ISSUE THREAD

**Issue by wolkenschieber** [klausmeyer/docker-registry-browser#515]
The configuration environment variable `SORT_TAGS_BY` doesn't accept [option](https://github.com/klausmeyer/docker-registry-browser/blob/master/docs/README.md#sort_tags_by) `version` in current `latest`. If the `version` is provided, the container refuses to start and following exception is thrown:
```
! Unable to load application: ArgumentError: SORT_TAGS_BY must be one of ["api", "name"]
/app/lib/config.rb:13:in `get': SORT_TAGS_BY must be one of ["api", "name"] (ArgumentError)
	from /app/config/initializers/settings.rb:14:in `block in <main>'
	from <internal:kernel>:90:in `tap'
	from /app/config/initializers/settings.rb:3:in `<main>'
	from /usr/local/bundle/gems/railties-7.0.4/lib/rails/engine.rb:667:in `load'
	from /usr/local/bundle/gems/railties-7.0.4/lib/rails/engine.rb:667:in `block in load_config_initializer'
	from /usr/local/bundle/gems/activesupport-7.0.4/lib/active_support/notifications.rb:208:in `instrument'
	from /usr/local/bundle/gems/railties-7.0.4/lib/rails/engine.rb:666:in `load_config_initializer'
	from /usr/local/bundle/gems/railties-7.0.4/lib/rails/engine.rb:620:in `block (2 levels) in <class:Engine>'
	from /usr/local/bundle/gems/railties-7.0.4/lib/rails/engine.rb:619:in `each'
	from /usr/local/bundle/gems/railties-7.0.4/lib/rails/engine.rb:619:in `block in <class:Engine>'
	from /usr/local/bundle/gems/railties-7.0.4/lib/rails/initializable.rb:32:in `instance_exec'
	from /usr/local/bundle/gems/railties-7.0.4/lib/rails/initializable.rb:32:in `run'
	from /usr/local/bundle/gems/railties-7.0.4/lib/rails/initializable.rb:61:in `block in run_initializers'
	from /usr/local/lib/ruby/3.1.0/tsort.rb:228:in `block in tsort_each'
	from /usr/local/lib/ruby/3.1.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	from /usr/local/lib/ruby/3.1.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
	from /usr/local/lib/ruby/3.1.0/tsort.rb:431:in `each_strongly_connected_component_from'
	from /usr/local/lib/ruby/3.1.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
	from /usr/local/bundle/gems/railties-7.0.4/lib/rails/initializable.rb:50:in `each'
	from /usr/local/bundle/gems/railties-7.0.4/lib/rails/initializable.rb:50:in `tsort_each_child'
	from /usr/local/lib/ruby/3.1.0/tsort.rb:415:in `call'
	from /usr/local/lib/ruby/3.1.0/tsort.rb:415:in `each_strongly_connected_component_from'
	from /usr/local/lib/ruby/3.1.0/tsort.rb:349:in `block in each_strongly_connected_component'
	from /usr/local/lib/ruby/3.1.0/tsort.rb:347:in `each'
	from /usr/local/lib/ruby/3.1.0/tsort.rb:347:in `call'
	from /usr/local/lib/ruby/3.1.0/tsort.rb:347:in `each_strongly_connected_component'
	from /usr/local/lib/ruby/3.1.0/tsort.rb:226:in `tsort_each'
	from /usr/local/lib/ruby/3.1.0/tsort.rb:205:in `tsort_each'
	from /usr/local/bundle/gems/railties-7.0.4/lib/rails/initializable.rb:60:in `run_initializers'
	from /usr/local/bundle/gems/railties-7.0.4/lib/rails/application.rb:372:in `initialize!'
	from /app/config/environment.rb:5:in `<top (required)>'
	from config.ru:3:in `require_relative'
	from config.ru:3:in `block in <main>'
	from /usr/local/bundle/gems/rack-2.2.4/lib/rack/builder.rb:116:in `eval'
	from /usr/local/bundle/gems/rack-2.2.4/lib/rack/builder.rb:116:in `new_from_string'
	from /usr/local/bundle/gems/rack-2.2.4/lib/rack/builder.rb:105:in `load_file'
	from /usr/local/bundle/gems/rack-2.2.4/lib/rack/builder.rb:66:in `parse_file'
	from /usr/local/bundle/gems/puma-5.6.5/lib/puma/configuration.rb:348:in `load_rackup'
	from /usr/local/bundle/gems/puma-5.6.5/lib/puma/configuration.rb:270:in `app'
	from /usr/local/bundle/gems/puma-5.6.5/lib/puma/runner.rb:150:in `load_and_bind'
	from /usr/local/bundle/gems/puma-5.6.5/lib/puma/single.rb:44:in `run'
	from /usr/local/bundle/gems/puma-5.6.5/lib/puma/launcher.rb:193:in `run'
	from /usr/local/bundle/gems/puma-5.6.5/lib/puma/cli.rb:81:in `run'
	from /usr/local/bundle/gems/puma-5.6.5/bin/puma:10:in `<top (required)>'
	from /usr/local/bundle/bin/puma:25:in `load'
	from /usr/local/bundle/bin/puma:25:in `<main>'
```

**Comment by klausmeyer** [comment]
Thanks for reporting. I've pushed a fix and it will be available as `latest` tag soon.
