### ISSUE TITLE
Error with multi-platform images

### ISSUE THREAD

**Issue by chhe** [klausmeyer/docker-registry-browser#545]
Browsing tags which are created as multi-platform images produce an error in the UI: 

`We're sorry, but something went wrong.
If you are the application owner check the logs for more information.`

Error Log in registry-browser:

```
I, [2023-02-14T10:26:57.069680 #1]  INFO -- request: [0f05d7d3-dfd2-40e5-a8a9-4ce2ef2e7a1b] GET http://XXXXX:XXXX/v2/ubuntu-base/manifests/latest
I, [2023-02-14T10:26:57.170969 #1]  INFO -- : [0f05d7d3-dfd2-40e5-a8a9-4ce2ef2e7a1b] Completed 500 Internal Server Error in 211ms (Allocations: 1696)
F, [2023-02-14T10:26:57.172148 #1] FATAL -- : [0f05d7d3-dfd2-40e5-a8a9-4ce2ef2e7a1b]
[0f05d7d3-dfd2-40e5-a8a9-4ce2ef2e7a1b] Faraday::ResourceNotFound (the server responded with status 404):
[0f05d7d3-dfd2-40e5-a8a9-4ce2ef2e7a1b]
[0f05d7d3-dfd2-40e5-a8a9-4ce2ef2e7a1b] app/models/tag.rb:30:in `fetch_manifest'
[0f05d7d3-dfd2-40e5-a8a9-4ce2ef2e7a1b] app/models/tag.rb:36:in `fetch_manifests'
[0f05d7d3-dfd2-40e5-a8a9-4ce2ef2e7a1b] app/models/tag.rb:20:in `initialize'
[0f05d7d3-dfd2-40e5-a8a9-4ce2ef2e7a1b] app/models/tag.rb:14:in `new'
[0f05d7d3-dfd2-40e5-a8a9-4ce2ef2e7a1b] app/models/tag.rb:14:in `find'
[0f05d7d3-dfd2-40e5-a8a9-4ce2ef2e7a1b] app/controllers/tags_controller.rb:31:in `find_tag'
```

Error Log in Registry:

```
time="2023-02-14T11:26:57.169073076+01:00" level=error msg="response completed with error" err.code="manifest unknown" err.message="OCI index found, but accept header does not support OCI indexes" go.version=go1.16.15 http.request.host="XXXXX:XXXX" http.request.id=4543e24a-4350-4a71-9d1b-8b8e1d8fd0b5 http.request.method=GET http.request.remoteaddr="172.17.0.1:43226" http.request.uri="/v2/ubuntu-base/manifests/latest" http.request.useragent="Faraday v1.10.3" http.response.contenttype="application/json; charset=utf-8" http.response.duration=6.262585ms http.response.status=404 http.response.written=117 vars.name="ubuntu-base" vars.reference=latest
```

Image ist created and pushed with `docker buildx build`:

```
docker buildx build --compress --platform linux/arm64,linux/amd64 -tXXXXX:XXXX/ubuntu-base:latest -f Dockerfile . --push
```

Docker version info:

```
Client: Docker Engine - Community
 Version:           v23.0.1
 API version:       1.42
 Go version:        go1.19.5
 Git commit:        a5ee5b1
 Built:             Sun Feb 12 10:51:47 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          v23.0.1
  API version:      1.42 (minimum version 1.12)
  Go version:       go1.19.5
  Git commit:       bc3805a
  Built:            Sun Feb 12 10:49:50 2023
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          1.6.16
  GitCommit:        31aa4358a36870b21a992d3ad2bef29e1d693bec
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Comment by klausmeyer** [comment]
Hi @chhe,

thanks for reporting and also providing a PR with a possible fix.

I would like to reproduce the issue but so far I'm having no luck.

A image pushed with the `buildx` command like yours is shown fine in my registry:

<img width="952" alt="Screenshot 2023-02-14 at 17 40 05" src="https://user-images.githubusercontent.com/615777/218800775-47642e6f-3541-4806-99e2-e0b69288335a.png">

Could you please share what exactly version of the registry itself and the docker-registry-browser application you're using?

I tried with:

* `registry:2.8.1`
* `klausmeyer/docker-registry-browser@sha256:930b81c1fa4e172332886f5786ee515171662032a1ae63eefaa32de9d79ab600` (git: 2c3288b, latest from 3 days ago)

**Comment by chhe** [comment]
That is very strange. I'm running `registry:2.8.1` and `klausmeyer/docker-registry-browser@sha256:930b81c1fa4e172332886f5786ee515171662032a1ae63eefaa32de9d79ab600` too.

My guess is, it has something to do with the two manifests im filtering out in my fix. both have an "unknown" for architecture and os.

**Comment by chhe** [comment]
I was suspecting that maybe something was wrong with my registry so I did a clean install. Unfortunately I see the same behavior.

**Comment by klausmeyer** [comment]
Ok, that's weird.

Could you provide some more information about that `manifest` with `os` or `architecture` being returned as `unknown`?

For example via some simple puts debugging:

```diff
self.manifests = fetch_manifests.find_all { |manifest| 
+ puts manifest
  manifest.architecture() != "unknown" && manifest.os() != "unknown"
}.sort_by(&:architecture)
```

**Comment by chhe** [comment]
Instead of doing that I went back to the beginning. Here is what the registry repsonds with upon querying an affected tag:

```
$ curl -H "Accept: application/vnd.oci.image.index.v1+json" http://docker-registry/v2/alpine-locale/manifests/latest

{
  "mediaType": "application/vnd.oci.image.index.v1+json",
  "schemaVersion": 2,
  "manifests": [
    {
      "mediaType": "application/vnd.oci.image.manifest.v1+json",
      "digest": "sha256:0b2a9c4f83d80c475a4d0a9822d133b6b94da574d2524576f68531404ab07cbf",
      "size": 863,
      "platform": {
        "architecture": "arm64",
        "os": "linux"
      }
    },
    {
      "mediaType": "application/vnd.oci.image.manifest.v1+json",
      "digest": "sha256:16fec09941d77d163521edae7843219cbad5bcc342574d5bc6e15d245138b3b1",
      "size": 863,
      "platform": {
        "architecture": "amd64",
        "os": "linux"
      }
    },
    {
      "mediaType": "application/vnd.oci.image.manifest.v1+json",
      "digest": "sha256:be3d799c6bf2c32bd81bc79c5879e8303c6b209f92ce3c48ec96a9235edf2c22",
      "size": 566,
      "annotations": {
        "vnd.docker.reference.digest": "sha256:0b2a9c4f83d80c475a4d0a9822d133b6b94da574d2524576f68531404ab07cbf",
        "vnd.docker.reference.type": "attestation-manifest"
      },
      "platform": {
        "architecture": "unknown",
        "os": "unknown"
      }
    },
    {
      "mediaType": "application/vnd.oci.image.manifest.v1+json",
      "digest": "sha256:cc9152eef644ba2d5f1541c64948576e6deebf0855c2859a8dcbf3a8605280e0",
      "size": 566,
      "annotations": {
        "vnd.docker.reference.digest": "sha256:16fec09941d77d163521edae7843219cbad5bcc342574d5bc6e15d245138b3b1",
        "vnd.docker.reference.type": "attestation-manifest"
      },
      "platform": {
        "architecture": "unknown",
        "os": "unknown"
      }
    }
  ]
}
```

The last two manifests are the ones I'm filtering with the "unknown"- check. It seems they are a special type of manifest (https://docs.docker.com/build/attestations/attestation-storage/#attestation-manifest). Maybe it would be better to filter on the type instead of the "unknown"- check?

And here is the response for one of the "unknown"- manifests:

```
curl -H "Accept: application/vnd.oci.image.manifest.v1+json" http://docker-registry/v2/alpine-locale/manifests/sha256:cc91
52eef644ba2d5f1541c64948576e6deebf0855c2859a8dcbf3a8605280e0
{
  "mediaType": "application/vnd.oci.image.manifest.v1+json",
  "schemaVersion": 2,
  "config": {
    "mediaType": "application/vnd.oci.image.config.v1+json",
    "digest": "sha256:824dbb11ee1636e3882be6921fd452b0bd7b97c1a61f337123389968777111e2",
    "size": 167
  },
  "layers": [
    {
      "mediaType": "application/vnd.in-toto+json",
      "digest": "sha256:12fd574284229bb9fe1269d2da75f48cda1e7f5f2efe932f17625e5dc9b0781a",
      "size": 1338,
      "annotations": {
        "in-toto.io/predicate-type": "https://slsa.dev/provenance/v0.2"
      }
    }
  ]
}
```

**Comment by klausmeyer** [comment]
Ah ok - that makes sense now. Attestations I didn't had on my radar at all.

Guess your approach of using the "unknown" value to filter them out is good enough.

I would only need some specs in your PR to merge it. Would you like to take care of that yourself or should I add them?

**Comment by chhe** [comment]
I'm not a ruby developer at all so it would be cool if you could add them. I did make the changes to the method calls you aksed for in PR though.

**Comment by klausmeyer** [comment]
Ok. Will look into it soon.

**Comment by klausmeyer** [comment]
I've made a few modifications now and merged the PR.

Please give it a try once the new `latest` tag is ready.

**Comment by chhe** [comment]
Works with the newest latest tag from docker hub.
