### ISSUE TITLE
Error Displaying Tag Info

### ISSUE THREAD

**Issue by darktempla** [klausmeyer/docker-registry-browser#574]
Hi thanks again for a great front-end for docker registries. 
I have been using this application for about 2+ years in my homelab and it does a really good job.
So hopefully you can figure out a fix for this one, some information below to help you out. 

One issue I have noticed lately is when I attempt to view the tags of some images the application fails when displaying the tag information and displays an error message.

It turns out that the images with problems are multi-arch images I produce using "docker buildx" command.  
Potentially they are publishing now in a new format (prehaps OCI), not sure.

In the application logs I see:
```bash
I, [2023-06-13T11:35:04.971502 #1]  INFO -- request: [4d128621-2091-4acb-84d9-33a823b75302] GET https://192.168.0.17:5001/v2/data-sync/manifests/feature-cicd
I, [2023-06-13T11:35:05.190960 #1]  INFO -- : [4d128621-2091-4acb-84d9-33a823b75302] Completed 500 Internal Server Error in 437ms (Allocations: 1901)
F, [2023-06-13T11:35:05.192961 #1] FATAL -- : [4d128621-2091-4acb-84d9-33a823b75302]
[4d128621-2091-4acb-84d9-33a823b75302] Faraday::ResourceNotFound (the server responded with status 404):
[4d128621-2091-4acb-84d9-33a823b75302]
[4d128621-2091-4acb-84d9-33a823b75302] app/models/tag.rb:30:in `fetch_manifest'
[4d128621-2091-4acb-84d9-33a823b75302] app/models/tag.rb:36:in `fetch_manifests'
[4d128621-2091-4acb-84d9-33a823b75302] app/models/tag.rb:20:in `initialize'
[4d128621-2091-4acb-84d9-33a823b75302] app/models/tag.rb:14:in `new'
[4d128621-2091-4acb-84d9-33a823b75302] app/models/tag.rb:14:in `find'
[4d128621-2091-4acb-84d9-33a823b75302] app/controllers/tags_controller.rb:31:in `find_tag'
```
When I run the command myself it gave me more context.

**No accept headers:**
```bash
$ http --verify=no -a user:pass https://192.168.0.17:5001/v2/data-sync/manifests/feature-cicd

HTTP/1.1 404 Not Found
Content-Length: 117
Content-Type: application/json; charset=utf-8
Date: Tue, 13 Jun 2023 11:42:36 GMT
Docker-Distribution-Api-Version: registry/2.0
X-Content-Type-Options: nosniff

{
    "errors": [
        {
            "code": "MANIFEST_UNKNOWN",
            "message": "OCI index found, but accept header does not support OCI indexes"
        }
    ]
}
```
**With `application/vnd.oci.image.manifest.v1+json` header:**
```bash
$ http --verify=no -a user:pass https://192.168.0.17:5001/v2/data-sync/manifests/feature-cicd \
Accept:application/vnd.oci.image.manifest.v1+json

HTTP/1.1 404 Not Found
Content-Length: 117
Content-Type: application/json; charset=utf-8
Date: Tue, 13 Jun 2023 11:44:48 GMT
Docker-Distribution-Api-Version: registry/2.0
X-Content-Type-Options: nosniff

{
    "errors": [
        {
            "code": "MANIFEST_UNKNOWN",
            "message": "OCI index found, but accept header does not support OCI indexes"
        }
    ]
}
```
**With `application/vnd.oci.image.index.v1+json` header (Potential FIX):**
```bash
$ http --verify=no -a user:pass https://192.168.0.17:5001/v2/data-sync/manifests/feature-cicd \
Accept:application/vnd.oci.image.index.v1+json

HTTP/1.1 200 OK
Content-Length: 1609
Content-Type: application/vnd.oci.image.index.v1+json
Date: Tue, 13 Jun 2023 11:46:30 GMT
Docker-Content-Digest: sha256:140938d31c19d8be9ba13cca8239f482dee646f5b502d7f070d10bfe5c2140e0
Docker-Distribution-Api-Version: registry/2.0
Etag: "sha256:140938d31c19d8be9ba13cca8239f482dee646f5b502d7f070d10bfe5c2140e0"
X-Content-Type-Options: nosniff

{
    "manifests": [
        {
            "digest": "sha256:002ae9decceba58e169ca416561d7b7f5d7fdd700054fe5a114b7bfc95c211b8",
            "mediaType": "application/vnd.oci.image.manifest.v1+json",
            "platform": {
                "architecture": "amd64",
                "os": "linux"
            },
            "size": 1818
        },
        {
            "digest": "sha256:31f19e8f67a19d6d281d43d4411f9dcdafdedb940fd65792c17c25f5412e2740",
            "mediaType": "application/vnd.oci.image.manifest.v1+json",
            "platform": {
                "architecture": "arm64",
                "os": "linux"
            },
            "size": 1818
        },
        {
            "annotations": {
                "vnd.docker.reference.digest": "sha256:002ae9decceba58e169ca416561d7b7f5d7fdd700054fe5a114b7bfc95c211b8",
                "vnd.docker.reference.type": "attestation-manifest"
            },
            "digest": "sha256:525471f1f598f7b425a9fcd1ae6bc63b2c4a7febd4279bf266d6a0f331189b78",
            "mediaType": "application/vnd.oci.image.manifest.v1+json",
            "platform": {
                "architecture": "unknown",
                "os": "unknown"
            },
            "size": 566
        },
        {
            "annotations": {
                "vnd.docker.reference.digest": "sha256:31f19e8f67a19d6d281d43d4411f9dcdafdedb940fd65792c17c25f5412e2740",
                "vnd.docker.reference.type": "attestation-manifest"
            },
            "digest": "sha256:2806fe115c09bd4f474be0eaf80fd4925b8237c1efe46617e85fa7e1882ec608",
            "mediaType": "application/vnd.oci.image.manifest.v1+json",
            "platform": {
                "architecture": "unknown",
                "os": "unknown"
            },
            "size": 566
        }
    ],
    "mediaType": "application/vnd.oci.image.index.v1+json",
    "schemaVersion": 2
}
```

**Comment by klausmeyer** [comment]
Hi @darktempla,

this looks very much like the issue reported in #545 and addressed in #546

What exact version are you running?
