### ISSUE TITLE
Can't authenticate to dockerhub

### ISSUE THREAD

**Issue by dannysauer** [klausmeyer/docker-registry-browser#658]
I have some private registries on dockerhub which I want some users to be able to browse.  Theusers only have PATs; they do not have "real" console passwords, so they can't log in to Dockerhub's web console.

I eventually got this thing stood up on k8s via the helm chart, and now authentication doesn't seem to work.  It detects that auth is necessary, but the auth flow doesn't work.

```plain
I, [2024-07-31T23:14:55.246391 #1]  INFO -- : [a6f50e2f-0a0d-41db-9fa5-8f2576ff73e9] Started GET "/" for _redacted_ at 2024-07-31 23:14:55 +0000
I, [2024-07-31T23:14:55.249000 #1]  INFO -- : [a6f50e2f-0a0d-41db-9fa5-8f2576ff73e9] Processing by RepositoriesController#index as HTML
I, [2024-07-31T23:14:55.249838 #1]  INFO -- request: [a6f50e2f-0a0d-41db-9fa5-8f2576ff73e9] GET https://registry-1.docker.io/v2/_catalog?n=100
I, [2024-07-31T23:14:55.383349 #1]  INFO -- request: [a6f50e2f-0a0d-41db-9fa5-8f2576ff73e9] GET https://auth.docker.io/token?client_id=docker-registry-browser&offline_token=true&scope=registry%3Acatalog%3A%2A&service=registry.docker.io
I, [2024-07-31T23:14:55.546061 #1]  INFO -- : [a6f50e2f-0a0d-41db-9fa5-8f2576ff73e9] Completed 500 Internal Server Error in 297ms (Allocations: 2393)
E, [2024-07-31T23:14:55.546935 #1] ERROR -- : [a6f50e2f-0a0d-41db-9fa5-8f2576ff73e9]   
[a6f50e2f-0a0d-41db-9fa5-8f2576ff73e9] Faraday::BadRequestError (the server responded with status 400):
[a6f50e2f-0a0d-41db-9fa5-8f2576ff73e9]   
[a6f50e2f-0a0d-41db-9fa5-8f2576ff73e9] app/services/obtain_authentication_token.rb:20:in `perform_request'
[a6f50e2f-0a0d-41db-9fa5-8f2576ff73e9] app/services/obtain_authentication_token.rb:12:in `call'
[a6f50e2f-0a0d-41db-9fa5-8f2576ff73e9] app/controllers/application_controller.rb:59:in `obtain_authentication_token'
[a6f50e2f-0a0d-41db-9fa5-8f2576ff73e9] app/controllers/application_controller.rb:37:in `token_authentication'
[a6f50e2f-0a0d-41db-9fa5-8f2576ff73e9] app/controllers/application_controller.rb:25:in `client_error'
```

This happens with PATs or legit passwords.  As I don't control the registry (oh, what I'd change if I ran dockerhub), I don't have any registry-side logs. :/

**Comment by klausmeyer** [comment]
Hi @dannysauer,

I must say what you're trying to archive is a bit unusual as the application was designed to be used with private registries and not the dockerhub ;) I am not even sure if it's technically possible with the current setup.

Anyways - it would be interesting what the auth-server is returning with that HTTP 400 response. Can you start the application with `RAILS_LOG_LEVEL=debug` to have it (hopefully) print a bit more information?

**Comment by klausmeyer** [comment]
Please ignore my request / question. I did try it on my own and I'm getting this error:

```
{"details":"unknown resource type"}
```

It looks like if the dockerhub auth-server wouldn't allow fetching the catalog of available images - what would match with what is written in this article: https://toddysm.com/2024/01/30/authenticating-with-oci-registries-docker-hub-implementation/

When I try accessing an image directly (via manually opening the `/repo/xxx/yyy` URL) I am able to successfully authenticate - but running into another issue then with the returned token being to big to put into the session cookie.

**Comment by dannysauer** [comment]
Dang. I really just wanted to see a specific namespace, so figured I'd need to tweak the application anyway to reduce the kajillion namespace to just the two I want. 😂 So thanks for looking in to it before I started!
